apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-hello-world
  template:
    metadata:
      labels:
        app: spring-boot-hello-world
    spec:
      containers:
      - name: spring-boot-hello-world
        image: muttalipsahin/spring-boot-hello-world:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
